In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import csv
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
import random

The textconverter.csv file contains all the links on https://scrapsfromtheloft.com/stand-up-comedy-scripts/ containing 'comedy' and 'transcript'. The process was:
1. Extract links from site using https://simplescraper.io/extracturls and filter for the word "comedy"
2. Put the resulting txt file into https://textconverter.com/filter-text and filter for the word "transcript"
3. Put the resulting txt file into https://convertio.co/txt-csv/ to convert it to a csv

In [ ]:
links_csv = "/textconverter.csv"
urls = pd.read_csv(links_csv, header=None)[0].tolist()
session = None
headers = None

In [4]:
df_json = "/content/4300_articles.json"
df = pd.read_json(df_json, lines=True)
df

,url,title,content
0,https://scrapsfromtheloft.com/comedy/gary-gulm...,Gary Gulman: The Great Depresh (2019) | Transc...,Gary Gulman\n‘s 2019 HBO stand-up comedy speci...
1,https://scrapsfromtheloft.com/comedy/ricky-ger...,Ricky Gervais: Armageddon (2023) | Transcript,Ricky Gervais: Armageddon\nis packed with\nGer...
2,https://scrapsfromtheloft.com/comedy/gary-gulm...,Gary Gulman: It’s About Time (2016) | Transcript,Imagine stepping into the mind of a comedic wh...
3,https://scrapsfromtheloft.com/comedy/orny-adam...,None,None
4,https://scrapsfromtheloft.com/comedy/dave-chap...,Dave Chappelle: The Dreamer (2023) | Transcript,"“The Dreamer,” which was shot in\nChappelle\n’..."
...,...,...,...
588,https://scrapsfromtheloft.com/comedy/sebastian...,None,None
589,https://scrapsfromtheloft.com/comedy/rory-scov...,None,None
590,https://scrapsfromtheloft.com/comedy/robby-hof...,None,None
591,https://scrapsfromtheloft.com/comedy/robby-hof...,None,None
592,https://scrapsfromtheloft.com/comedy/dave-chap...,Dave Chappelle: The Unstoppable (2025) | Trans...,Dave Chappelle: The Unstoppable (2025)\nReleas...

In [5]:
df_missing = df[df['title'].isna()]
urls_missing = df_missing['url'].to_list()
urls_missing

['https://scrapsfromtheloft.com/comedy/orny-adams-more-than-loud-transcript/',
 'https://scrapsfromtheloft.com/comedy/lisa-lampanelli-back-to-the-drawing-board-2015-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/jeff-foxworthy-totally-committed-transcript/',
 'https://scrapsfromtheloft.com/comedy/election-results-2020-last-week-tonight-with-john-oliver-transcript/',
 'https://scrapsfromtheloft.com/comedy/dave-chappelle-worth-2004-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/dave-chappelle-equanimity-2017-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/roy-wood-jr-father-figure-transcript/',
 'https://scrapsfromtheloft.com/comedy/amanda-seales-i-be-knowin-transcript/',
 'https://scrapsfromtheloft.com/comedy/arsenio-hall-smart-and-classy-transcript/',
 'https://scrapsfromtheloft.com/comedy/aziz-ansari-right-now-transcript/',
 'https://scrapsfromtheloft.com/comedy/the-standups-gina-yashere-2018-transcript/',
 'https://scrapsfromtheloft.com/comedy/dave-chappelle-age-spin-2017-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/wanda-sykes-not-normal-transcript/',
 'https://scrapsfromtheloft.com/comedy/cedric-the-entertainer-live-from-the-ville-transcript/',
 'https://scrapsfromtheloft.com/comedy/eddie-murphy-raw-transcript/',
 'https://scrapsfromtheloft.com/comedy/w-kamau-bell-private-school-negro-transcript/',
 'https://scrapsfromtheloft.com/comedy/kevin-hart-irresponsible-transcript/',
 'https://scrapsfromtheloft.com/comedy/eddie-griffin-bible-negro-version-transcript/',
 'https://scrapsfromtheloft.com/comedy/robin-williams-weapons-of-self-destruction-transcript/',
 'https://scrapsfromtheloft.com/comedy/latin-history-for-morons-john-leguizamo-transcript/',
 'https://scrapsfromtheloft.com/comedy/oh-hello-on-broadway-transcript/',
 'https://scrapsfromtheloft.com/comedy/bo-burnham-what-transcript/',
 'https://scrapsfromtheloft.com/comedy/ellen-degeneres-relatable-transcript/',
 'https://scrapsfromtheloft.com/comedy/david-chappelles-snl-monologue-2016-transcript/',
 'https://scrapsfromtheloft.com/comedy/iliza-shlesinger-war-paint-transcript/',
 'https://scrapsfromtheloft.com/comedy/deray-davis-how-to-act-black-transcript/',
 'https://scrapsfromtheloft.com/comedy/eddie-griffin-undeniable-2018-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/d-l-hughley-unapologetic-transcript/',
 'https://scrapsfromtheloft.com/comedy/chris-tucker-live-2015-transcript/',
 'https://scrapsfromtheloft.com/comedy/kevin-hart-let-me-explain-2013-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/kevin-hart-what-now-2016-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/richard-pryor-live-and-smokin-1971-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/neal-brennan-women-and-black-dudes-transcript/',
 'https://scrapsfromtheloft.com/comedy/eddie-griffin-can-tell-em-i-said-transcript/',
 'https://scrapsfromtheloft.com/comedy/eddie-murphy-delirious-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/us-history-last-week-tonight-with-john-oliver-transcript/',
 'https://scrapsfromtheloft.com/comedy/trevor-noah-afraid-dark-2017-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/jim-norton-monster-rain-transcript/',
 'https://scrapsfromtheloft.com/comedy/ralphie-may-filthy-animal-tour-transcript/',
 'https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-2-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/comedy-central-presents-tom-segura-s15e01-transcript/',
 'https://scrapsfromtheloft.com/comedy/john-mulaney-snl-monologue-2020-transcript/',
 'https://scrapsfromtheloft.com/comedy/bill-burr-snl-monologue-2020-transcript/',
 'https://scrapsfromtheloft.com/comedy/jim-norton-contextually-inadequate-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/stewart-lee-standup-comedian-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/russell-howard-live-dingledodies-2009-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/sarah-silverman-jesus-is-magic-2005-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/dylan-moran-off-the-hook-2015-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/jim-norton-mouthful-shame-transcript/',
 'https://scrapsfromtheloft.com/comedy/lenny-bruce-berkeley-concert-1965-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/trevor-noah-lost-translation-2015-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/craig-ferguson-just-being-honest-transcript/',
 'https://scrapsfromtheloft.com/comedy/craig-ferguson-a-wee-bit-o-revolution-transcript/',
 'https://scrapsfromtheloft.com/comedy/craig-ferguson-does-this-need-to-be-said-transcript/',
 'https://scrapsfromtheloft.com/comedy/larry-the-cable-guy-remain-seated-transcript/',
 'https://scrapsfromtheloft.com/comedy/kevin-hart-zero-fks-given-2020-transcript/',
 'https://scrapsfromtheloft.com/comedy/dave-chappelle-hbo-comedy-half-hour-1998-transcript/',
 'https://scrapsfromtheloft.com/comedy/bert-kreischer-fighting-a-bear-transcript/',
 'https://scrapsfromtheloft.com/comedy/bert-kreischer-hey-big-boy-transcript/',
 'https://scrapsfromtheloft.com/comedy/vir-das-outside-in-the-lockdown-special-transcript/',
 'https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-1-transcript/',
 'https://scrapsfromtheloft.com/comedy/bo-burnham-words-words-words-transcript/',
 'https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-3-transcript/',
 'https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-5-transcript/',
 'https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-6-transcript/',
 'https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-7-transcript/',
 'https://scrapsfromtheloft.com/comedy/jerry-seinfeld-23-hours-to-kill-transcript/',
 'https://scrapsfromtheloft.com/comedy/bill-burr-paper-tiger-transcript/',
 'https://scrapsfromtheloft.com/comedy/tom-segura-completely-normal-2014-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/tom-segura-overdoses-this-is-not-happening-transcript/',
 'https://scrapsfromtheloft.com/comedy/katt-williams-great-america-transcript/',
 'https://scrapsfromtheloft.com/comedy/end-of-trump-presidency-late-night-with-seth-meyers-transcript/',
 'https://scrapsfromtheloft.com/comedy/brian-regan-on-the-rocks-transcript/',
 'https://scrapsfromtheloft.com/comedy/sarah-cooper-everythings-fine-transcript/',
 'https://scrapsfromtheloft.com/comedy/mark-normand-dont-be-yourself-transcript/',
 'https://scrapsfromtheloft.com/comedy/dave-chappelle-deep-heart-texas-2017-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/joe-list-i-hate-myself-transcript/',
 'https://scrapsfromtheloft.com/comedy/justice-society-world-war-ii-transcript/',
 'https://scrapsfromtheloft.com/comedy/tig-notaro-boyish-girl-interrupted-transcript/',
 'https://scrapsfromtheloft.com/comedy/paul-mooney-piece-mind-godbless-america-transcript/',
 'https://scrapsfromtheloft.com/comedy/fatherhood-2021-movie-transcript/',
 'https://scrapsfromtheloft.com/comedy/tom-papa-human-mule-transcript/',
 'https://scrapsfromtheloft.com/comedy/tom-papa-freaked-out-transcript/',
 'https://scrapsfromtheloft.com/comedy/tom-papa-youre-doing-great-transcript/',
 'https://scrapsfromtheloft.com/comedy/mike-birbiglia-my-girlfriends-boyfriend-2013-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/jerry-seinfeld-im-telling-you-for-the-last-time-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/joe-rogan-triggered-2016-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/anthony-jeselnik-fire-in-the-maternity-ward-transcript/',
 'https://scrapsfromtheloft.com/comedy/bombshell-emails-reveal-trump-planned-coup-with-loyalist-jeffrey-clark-a-closer-look-transcript/',
 'https://scrapsfromtheloft.com/comedy/tiffany-haddish-black-mitzvah-transcript/',
 'https://scrapsfromtheloft.com/comedy/marlon-wayans-wokeish-transcript/',
 'https://scrapsfromtheloft.com/comedy/george-carlin-jamming-new-york-1992-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/george-carlin-doin-it-again-transcript/',
 'https://scrapsfromtheloft.com/comedy/donald-glover-weirdo-transcript/',
 'https://scrapsfromtheloft.com/comedy/phil-wang-philly-philly-wang-wang-transcript/',
 'https://scrapsfromtheloft.com/comedy/louis-c-k-live-at-the-beacon-theatre-2011-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/kathleen-madigan-madigan-again-transcript/',
 'https://scrapsfromtheloft.com/comedy/nate-bargatze-hello-world-transcript/',
 'https://scrapsfromtheloft.com/comedy/anjelah-johnson-not-fancy-transcript/',
 'https://scrapsfromtheloft.com/comedy/patton-oswalt-i-love-everything-transcript/',
 'https://scrapsfromtheloft.com/comedy/mike-epps-only-one-mike-transcript/',
 'https://scrapsfromtheloft.com/comedy/vir-das-fool-volume-transcript/',
 'https://scrapsfromtheloft.com/comedy/roy-wood-jr-no-one-loves-you-transcript/',
 'https://scrapsfromtheloft.com/comedy/sarah-silverman-postmortem-transcript/',
 'https://scrapsfromtheloft.com/comedy/steph-tolev-filth-queen-transcript/',
 'https://scrapsfromtheloft.com/comedy/mike-birbiglia-the-good-life-transcript/',
 'https://scrapsfromtheloft.com/comedy/david-spade-dandelion-transcript/',
 'https://scrapsfromtheloft.com/comedy/conan-obrien-mark-twain-prize-transcript/',
 'https://scrapsfromtheloft.com/comedy/jon-stewart-on-jimmy-kimmel-transcript/',
 'https://scrapsfromtheloft.com/comedy/sammy-obeid-charlie-kirk-america-turning-point-transcript/',
 'https://scrapsfromtheloft.com/comedy/vir-das-abroad-understanding-transcript/',
 'https://scrapsfromtheloft.com/comedy/george-carlin-you-are-all-diseased-transcript/',
 'https://scrapsfromtheloft.com/comedy/cristela-alonzo-lower-classy-2017-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/jimmy-kimmel-delivers-first-monologue-since-returning-transcript/',
 'https://scrapsfromtheloft.com/comedy/pablo-francisco-ouch-live-san-jose-2006-full-transcript/',
 'https://scrapsfromtheloft.com/comedy/eddie-izzard-definite-article-transcript/',
 'https://scrapsfromtheloft.com/comedy/jimmy-kimmels-suspension-was-always-about-censorship-transcript/',
 'https://scrapsfromtheloft.com/comedy/sammy-obeid-solving-charlie-kirk-murder-transcript/',
 'https://scrapsfromtheloft.com/comedy/rachel-sennott-the-worst-part-of-sitting-on-a-guys-face-transcript/',
 'https://scrapsfromtheloft.com/comedy/sammy-obeid-how-to-save-gaza-transcript/',
 'https://scrapsfromtheloft.com/comedy/michelle-wolf-the-well-transcript/',
 'https://scrapsfromtheloft.com/comedy/doug-stanhope-no-refunds-transcript/',
 'https://scrapsfromtheloft.com/comedy/malik-elassal-woke-flat-earthers-transcript/',
 'https://scrapsfromtheloft.com/comedy/deon-cole-ok-mister-2024-transcript/',
 'https://scrapsfromtheloft.com/comedy/sebastian-maniscalco-it-aint-right-transcript/',
 'https://scrapsfromtheloft.com/comedy/rory-scovel-on-religion-transcript/',
 'https://scrapsfromtheloft.com/comedy/robby-hoffman-im-nervous-transcript/',
 'https://scrapsfromtheloft.com/comedy/robby-hoffman-wake-up-2025-transcript/']

In [ ]:
def setup_session():
  session = requests.Session()

  headers = {
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/120.0 Safari/537.36"
  }

  session.headers.update(headers)

In [6]:
def scrape_page(link):
    try:
        time.sleep(random.uniform(2, 5))

        response = session.get(link, timeout=10)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, "html.parser")

        title_tag = soup.find("h1", class_="elementor-heading-title")
        title = title_tag.get_text(strip=True) if title_tag else None

        """
        <div class="elementor-element elementor-element-74af9a5b elementor-widget elementor-widget-theme-post-content" data-id="74af9a5b" data-element_type="widget" data-widget_type="theme-post-content.default" style="height: auto !important;">
        """
        content_div = soup.find("div", {"data-id": "74af9a5b"})
        content = content_div.get_text(separator="\n", strip=True) if content_div else None

        return {
            "url": link,
            "title": title,
            "content": content
        }

    except Exception as e:
        print(f"Failed: {link} | {e}")
        return {"url": link, "title": None, "content": None}

In [ ]:
records = []

session = requests.Session()

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/120.0 Safari/537.36"
}

session.headers.update(headers)

with ThreadPoolExecutor(max_workers=3) as executor:

    futures = [executor.submit(scrape_page, url) for url in urls]

    for future in as_completed(futures):
        records.append(future.result())

df = pd.DataFrame(records)

Failed: https://scrapsfromtheloft.com/comedy/orny-adams-more-than-loud-transcript/ | ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Failed: https://scrapsfromtheloft.com/comedy/lisa-lampanelli-back-to-the-drawing-board-2015-full-transcript/ | HTTPSConnectionPool(host='scrapsfromtheloft.com', port=443): Read timed out. (read timeout=10)
Failed: https://scrapsfromtheloft.com/comedy/jeff-foxworthy-totally-committed-transcript/ | ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Failed: https://scrapsfromtheloft.com/comedy/election-results-2020-last-week-tonight-with-john-oliver-transcript/ | 503 Server Error: Service Temporarily Unavailable for url: https://scrapsfromtheloft.com/comedy/election-results-2020-last-week-tonight-with-john-oliver-transcript/
Failed: https://scrapsfromtheloft.com/comedy/dave-chappelle-worth-2004-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/dave-chappelle-worth-2004-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/dave-chappelle-equanimity-2017-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/dave-chappelle-equanimity-2017-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/roy-wood-jr-father-figure-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/roy-wood-jr-father-figure-transcript/
Failed: https://scrapsfromtheloft.com/comedy/amanda-seales-i-be-knowin-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/amanda-seales-i-be-knowin-transcript/
Failed: https://scrapsfromtheloft.com/comedy/arsenio-hall-smart-and-classy-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/arsenio-hall-smart-and-classy-transcript/
Failed: https://scrapsfromtheloft.com/comedy/aziz-ansari-right-now-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/aziz-ansari-right-now-transcript/
Failed: https://scrapsfromtheloft.com/comedy/the-standups-gina-yashere-2018-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/the-standups-gina-yashere-2018-transcript/
Failed: https://scrapsfromtheloft.com/comedy/dave-chappelle-age-spin-2017-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/dave-chappelle-age-spin-2017-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/wanda-sykes-not-normal-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/wanda-sykes-not-normal-transcript/
Failed: https://scrapsfromtheloft.com/comedy/cedric-the-entertainer-live-from-the-ville-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/cedric-the-entertainer-live-from-the-ville-transcript/
Failed: https://scrapsfromtheloft.com/comedy/eddie-murphy-raw-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/eddie-murphy-raw-transcript/
Failed: https://scrapsfromtheloft.com/comedy/w-kamau-bell-private-school-negro-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/w-kamau-bell-private-school-negro-transcript/
Failed: https://scrapsfromtheloft.com/comedy/kevin-hart-irresponsible-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/kevin-hart-irresponsible-transcript/
Failed: https://scrapsfromtheloft.com/comedy/eddie-griffin-bible-negro-version-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/eddie-griffin-bible-negro-version-transcript/
Failed: https://scrapsfromtheloft.com/comedy/robin-williams-weapons-of-self-destruction-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/robin-williams-weapons-of-self-destruction-transcript/
Failed: https://scrapsfromtheloft.com/comedy/latin-history-for-morons-john-leguizamo-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/latin-history-for-morons-john-leguizamo-transcript/
Failed: https://scrapsfromtheloft.com/comedy/oh-hello-on-broadway-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/oh-hello-on-broadway-transcript/
Failed: https://scrapsfromtheloft.com/comedy/bo-burnham-what-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/bo-burnham-what-transcript/
Failed: https://scrapsfromtheloft.com/comedy/ellen-degeneres-relatable-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/ellen-degeneres-relatable-transcript/
Failed: https://scrapsfromtheloft.com/comedy/david-chappelles-snl-monologue-2016-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/david-chappelles-snl-monologue-2016-transcript/
Failed: https://scrapsfromtheloft.com/comedy/iliza-shlesinger-war-paint-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/iliza-shlesinger-war-paint-transcript/
Failed: https://scrapsfromtheloft.com/comedy/deray-davis-how-to-act-black-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/deray-davis-how-to-act-black-transcript/
Failed: https://scrapsfromtheloft.com/comedy/eddie-griffin-undeniable-2018-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/eddie-griffin-undeniable-2018-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/d-l-hughley-unapologetic-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/d-l-hughley-unapologetic-transcript/
Failed: https://scrapsfromtheloft.com/comedy/chris-tucker-live-2015-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/chris-tucker-live-2015-transcript/
Failed: https://scrapsfromtheloft.com/comedy/kevin-hart-let-me-explain-2013-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/kevin-hart-let-me-explain-2013-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/kevin-hart-what-now-2016-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/kevin-hart-what-now-2016-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/richard-pryor-live-and-smokin-1971-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/richard-pryor-live-and-smokin-1971-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/neal-brennan-women-and-black-dudes-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/neal-brennan-women-and-black-dudes-transcript/
Failed: https://scrapsfromtheloft.com/comedy/eddie-griffin-can-tell-em-i-said-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/eddie-griffin-can-tell-em-i-said-transcript/
Failed: https://scrapsfromtheloft.com/comedy/eddie-murphy-delirious-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/eddie-murphy-delirious-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/us-history-last-week-tonight-with-john-oliver-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/us-history-last-week-tonight-with-john-oliver-transcript/
Failed: https://scrapsfromtheloft.com/comedy/trevor-noah-afraid-dark-2017-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/trevor-noah-afraid-dark-2017-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/jim-norton-monster-rain-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/jim-norton-monster-rain-transcript/
Failed: https://scrapsfromtheloft.com/comedy/ralphie-may-filthy-animal-tour-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/ralphie-may-filthy-animal-tour-transcript/
Failed: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-2-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-2-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/comedy-central-presents-tom-segura-s15e01-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/comedy-central-presents-tom-segura-s15e01-transcript/
Failed: https://scrapsfromtheloft.com/comedy/john-mulaney-snl-monologue-2020-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/john-mulaney-snl-monologue-2020-transcript/
Failed: https://scrapsfromtheloft.com/comedy/bill-burr-snl-monologue-2020-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/bill-burr-snl-monologue-2020-transcript/
Failed: https://scrapsfromtheloft.com/comedy/jim-norton-contextually-inadequate-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/jim-norton-contextually-inadequate-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/stewart-lee-standup-comedian-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/stewart-lee-standup-comedian-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/russell-howard-live-dingledodies-2009-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/russell-howard-live-dingledodies-2009-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/sarah-silverman-jesus-is-magic-2005-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/sarah-silverman-jesus-is-magic-2005-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/dylan-moran-off-the-hook-2015-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/dylan-moran-off-the-hook-2015-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/jim-norton-mouthful-shame-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/jim-norton-mouthful-shame-transcript/
Failed: https://scrapsfromtheloft.com/comedy/lenny-bruce-berkeley-concert-1965-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/lenny-bruce-berkeley-concert-1965-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/trevor-noah-lost-translation-2015-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/trevor-noah-lost-translation-2015-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/craig-ferguson-just-being-honest-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/craig-ferguson-just-being-honest-transcript/
Failed: https://scrapsfromtheloft.com/comedy/craig-ferguson-a-wee-bit-o-revolution-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/craig-ferguson-a-wee-bit-o-revolution-transcript/
Failed: https://scrapsfromtheloft.com/comedy/craig-ferguson-does-this-need-to-be-said-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/craig-ferguson-does-this-need-to-be-said-transcript/
Failed: https://scrapsfromtheloft.com/comedy/larry-the-cable-guy-remain-seated-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/larry-the-cable-guy-remain-seated-transcript/
Failed: https://scrapsfromtheloft.com/comedy/kevin-hart-zero-fks-given-2020-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/kevin-hart-zero-fks-given-2020-transcript/
Failed: https://scrapsfromtheloft.com/comedy/dave-chappelle-hbo-comedy-half-hour-1998-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/dave-chappelle-hbo-comedy-half-hour-1998-transcript/
Failed: https://scrapsfromtheloft.com/comedy/bert-kreischer-fighting-a-bear-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/bert-kreischer-fighting-a-bear-transcript/
Failed: https://scrapsfromtheloft.com/comedy/bert-kreischer-hey-big-boy-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/bert-kreischer-hey-big-boy-transcript/
Failed: https://scrapsfromtheloft.com/comedy/vir-das-outside-in-the-lockdown-special-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/vir-das-outside-in-the-lockdown-special-transcript/
Failed: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-1-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-1-transcript/
Failed: https://scrapsfromtheloft.com/comedy/bo-burnham-words-words-words-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/bo-burnham-words-words-words-transcript/
Failed: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-3-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-3-transcript/
Failed: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-5-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-5-transcript/
Failed: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-6-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-6-transcript/
Failed: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-7-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-7-transcript/
Failed: https://scrapsfromtheloft.com/comedy/jerry-seinfeld-23-hours-to-kill-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/jerry-seinfeld-23-hours-to-kill-transcript/
Failed: https://scrapsfromtheloft.com/comedy/bill-burr-paper-tiger-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/bill-burr-paper-tiger-transcript/
Failed: https://scrapsfromtheloft.com/comedy/tom-segura-completely-normal-2014-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/tom-segura-completely-normal-2014-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/tom-segura-overdoses-this-is-not-happening-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/tom-segura-overdoses-this-is-not-happening-transcript/
Failed: https://scrapsfromtheloft.com/comedy/katt-williams-great-america-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/katt-williams-great-america-transcript/
Failed: https://scrapsfromtheloft.com/comedy/end-of-trump-presidency-late-night-with-seth-meyers-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/end-of-trump-presidency-late-night-with-seth-meyers-transcript/
Failed: https://scrapsfromtheloft.com/comedy/brian-regan-on-the-rocks-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/brian-regan-on-the-rocks-transcript/
Failed: https://scrapsfromtheloft.com/comedy/sarah-cooper-everythings-fine-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/sarah-cooper-everythings-fine-transcript/
Failed: https://scrapsfromtheloft.com/comedy/mark-normand-dont-be-yourself-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/mark-normand-dont-be-yourself-transcript/
Failed: https://scrapsfromtheloft.com/comedy/dave-chappelle-deep-heart-texas-2017-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/dave-chappelle-deep-heart-texas-2017-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/joe-list-i-hate-myself-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/joe-list-i-hate-myself-transcript/
Failed: https://scrapsfromtheloft.com/comedy/justice-society-world-war-ii-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/justice-society-world-war-ii-transcript/
Failed: https://scrapsfromtheloft.com/comedy/tig-notaro-boyish-girl-interrupted-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/tig-notaro-boyish-girl-interrupted-transcript/
Failed: https://scrapsfromtheloft.com/comedy/paul-mooney-piece-mind-godbless-america-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/paul-mooney-piece-mind-godbless-america-transcript/
Failed: https://scrapsfromtheloft.com/comedy/fatherhood-2021-movie-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/fatherhood-2021-movie-transcript/
Failed: https://scrapsfromtheloft.com/comedy/tom-papa-human-mule-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/tom-papa-human-mule-transcript/
Failed: https://scrapsfromtheloft.com/comedy/tom-papa-freaked-out-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/tom-papa-freaked-out-transcript/
Failed: https://scrapsfromtheloft.com/comedy/tom-papa-youre-doing-great-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/tom-papa-youre-doing-great-transcript/
Failed: https://scrapsfromtheloft.com/comedy/mike-birbiglia-my-girlfriends-boyfriend-2013-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/mike-birbiglia-my-girlfriends-boyfriend-2013-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/jerry-seinfeld-im-telling-you-for-the-last-time-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/jerry-seinfeld-im-telling-you-for-the-last-time-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/joe-rogan-triggered-2016-full-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/joe-rogan-triggered-2016-full-transcript/
Failed: https://scrapsfromtheloft.com/comedy/anthony-jeselnik-fire-in-the-maternity-ward-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/anthony-jeselnik-fire-in-the-maternity-ward-transcript/
Failed: https://scrapsfromtheloft.com/comedy/bombshell-emails-reveal-trump-planned-coup-with-loyalist-jeffrey-clark-a-closer-look-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/bombshell-emails-reveal-trump-planned-coup-with-loyalist-jeffrey-clark-a-closer-look-transcript/

In [8]:
records = []

session = requests.Session()

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/120.0 Safari/537.36"
}

session.headers.update(headers)

with ThreadPoolExecutor(max_workers=3) as executor:

    futures = [executor.submit(scrape_page, url) for url in urls_missing]

    for future in as_completed(futures):
        records.append(future.result())

df_filled = pd.DataFrame(records)

Failed: https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-6-transcript/ | ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [9]:
df_filled

,url,title,content
0,https://scrapsfromtheloft.com/comedy/jeff-foxw...,Jeff Foxworthy: Totally Committed (1998) – Ful...,"Ladies and gentlemen, please welcome Jeff Foxw..."
1,https://scrapsfromtheloft.com/comedy/lisa-lamp...,LISA LAMPANELLI: BACK TO THE DRAWING BOARD (20...,"Ladies and gentlemen, please welcome Lisa Lamp..."
2,https://scrapsfromtheloft.com/comedy/orny-adam...,Orny Adams: More Than Loud (2017) | Transcript,Title:\nOrny Adams: More Than Loud\nType:\nSta...
3,https://scrapsfromtheloft.com/comedy/election-...,Election Results 2020: Last Week Tonight with ...,Last Week Tonight with John Oliver\nSeason 7 E...
4,https://scrapsfromtheloft.com/comedy/dave-chap...,Dave Chappelle: Equanimity (2017) – Transcript,"“Equanimity” was shot in Washington, D.C., and..."
...,...,...,...
123,https://scrapsfromtheloft.com/comedy/deon-cole...,"Deon Cole: Ok, Mister (2024) | Transcript",[“Post That” by Deon Cole and Terry Hunter pla...
124,https://scrapsfromtheloft.com/comedy/sebastian...,Sebastian Maniscalco: It Ain’t Right (2025) | ...,Sebastian Maniscalco: It Ain’t Right (2025)\nD...
125,https://scrapsfromtheloft.com/comedy/rory-scov...,Rory Scovel on Religion,Rory Scovel\non\nreligion\nOne time my daughte...
126,https://scrapsfromtheloft.com/comedy/robby-hof...,Robby Hoffman: I’m Nervous (2019) | Transcript,Robby Hoffman: I’m Nervous\nis the debut one-h...
127,https://scrapsfromtheloft.com/comedy/robby-hof...,Robby Hoffman: Wake Up (2025) | Transcript,Robby Hoffman: Wake Up\nis the second hour-lon...

In [ ]:
# records = []

# for url in urls:
#     record = scrape_page(url)
#     records.append(record)
#     time.sleep(random.uniform(0.5, 2))


# df = pd.DataFrame(records)

Failed: https://scrapsfromtheloft.com/comedy/bill-maher-glad-david-koch-is-dead-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/bill-maher-glad-david-koch-is-dead-transcript/
Failed: https://scrapsfromtheloft.com/comedy/ryan-hamilton-stand-up-the-tonight-show-starring-jimmy-fallon-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/ryan-hamilton-stand-up-the-tonight-show-starring-jimmy-fallon-transcript/
Failed: https://scrapsfromtheloft.com/comedy/sebastian-maniscalco-tonight-show-starring-jimmy-fallon-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/sebastian-maniscalco-tonight-show-starring-jimmy-fallon-transcript/
Failed: https://scrapsfromtheloft.com/comedy/seth-meyers-2011-white-house-correspondents-dinner-transcript/ | 503 Server Error: Service Unavailable for url: https://scrapsfromtheloft.com/comedy/seth-meyers-2011-white-house-correspondents-dinner-transcript/

KeyboardInterrupt:

In [10]:
session = requests.Session()

headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/120.0 Safari/537.36"
}

session.headers.update(headers)

last_link = 'https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-6-transcript/'

last_data = scrape_page(last_link)
last_data

{'url': 'https://scrapsfromtheloft.com/comedy/sacha-baron-cohens-who-is-america-episode-6-transcript/',
 'title': 'Sacha Baron Cohen’s Who is America? – Episode 6 – Transcript',

In [28]:
df_filled.loc[df_filled['url'] == last_data['url'], ['title', 'content']] = [last_data['title'], last_data['content']]

In [29]:
df_filled[df_filled['url'] == last_data['url']]

,url,title,content
64,https://scrapsfromtheloft.com/comedy/sacha-bar...,Sacha Baron Cohen’s Who is America? – Episode ...,"Scenes:\nBilly Wayne Ruddick Jr., PhD intervie..."

In [37]:
df

,title,content
url,,
https://scrapsfromtheloft.com/comedy/jeff-foxworthy-totally-committed-transcript/,Jeff Foxworthy: Totally Committed (1998) – Ful...,"Ladies and gentlemen, please welcome Jeff Foxw..."
https://scrapsfromtheloft.com/comedy/lisa-lampanelli-back-to-the-drawing-board-2015-full-transcript/,LISA LAMPANELLI: BACK TO THE DRAWING BOARD (20...,"Ladies and gentlemen, please welcome Lisa Lamp..."
https://scrapsfromtheloft.com/comedy/orny-adams-more-than-loud-transcript/,Orny Adams: More Than Loud (2017) | Transcript,Title:\nOrny Adams: More Than Loud\nType:\nSta...
https://scrapsfromtheloft.com/comedy/election-results-2020-last-week-tonight-with-john-oliver-transcript/,Election Results 2020: Last Week Tonight with ...,Last Week Tonight with John Oliver\nSeason 7 E...
https://scrapsfromtheloft.com/comedy/dave-chappelle-equanimity-2017-full-transcript/,Dave Chappelle: Equanimity (2017) – Transcript,"“Equanimity” was shot in Washington, D.C., and..."
...,...,...
https://scrapsfromtheloft.com/comedy/sebastian-maniscalco-it-aint-right-transcript/,None,None
https://scrapsfromtheloft.com/comedy/rory-scovel-on-religion-transcript/,None,None
https://scrapsfromtheloft.com/comedy/robby-hoffman-im-nervous-transcript/,None,None
https://scrapsfromtheloft.com/comedy/robby-hoffman-wake-up-2025-transcript/,None,None
https://scrapsfromtheloft.com/comedy/dave-chappelle-unstoppable-transcript/,Dave Chappelle: The Unstoppable (2025) | Trans...,Dave Chappelle: The Unstoppable (2025)\nReleas...

In [38]:
df_filled = df_filled.set_index("url")

df.update(df_filled[['title', 'content']])

df = df.reset_index()
df

,url,title,content
0,https://scrapsfromtheloft.com/comedy/jeff-foxw...,Jeff Foxworthy: Totally Committed (1998) – Ful...,"Ladies and gentlemen, please welcome Jeff Foxw..."
1,https://scrapsfromtheloft.com/comedy/lisa-lamp...,LISA LAMPANELLI: BACK TO THE DRAWING BOARD (20...,"Ladies and gentlemen, please welcome Lisa Lamp..."
2,https://scrapsfromtheloft.com/comedy/orny-adam...,Orny Adams: More Than Loud (2017) | Transcript,Title:\nOrny Adams: More Than Loud\nType:\nSta...
3,https://scrapsfromtheloft.com/comedy/election-...,Election Results 2020: Last Week Tonight with ...,Last Week Tonight with John Oliver\nSeason 7 E...
4,https://scrapsfromtheloft.com/comedy/dave-chap...,Dave Chappelle: Equanimity (2017) – Transcript,"“Equanimity” was shot in Washington, D.C., and..."
...,...,...,...
588,https://scrapsfromtheloft.com/comedy/sebastian...,Sebastian Maniscalco: It Ain’t Right (2025) | ...,Sebastian Maniscalco: It Ain’t Right (2025)\nD...
589,https://scrapsfromtheloft.com/comedy/rory-scov...,Rory Scovel on Religion,Rory Scovel\non\nreligion\nOne time my daughte...
590,https://scrapsfromtheloft.com/comedy/robby-hof...,Robby Hoffman: I’m Nervous (2019) | Transcript,Robby Hoffman: I’m Nervous\nis the debut one-h...
591,https://scrapsfromtheloft.com/comedy/robby-hof...,Robby Hoffman: Wake Up (2025) | Transcript,Robby Hoffman: Wake Up\nis the second hour-lon...
592,https://scrapsfromtheloft.com/comedy/dave-chap...,Dave Chappelle: The Unstoppable (2025) | Trans...,Dave Chappelle: The Unstoppable (2025)\nReleas...

In [36]:
df.columns

Index(['title', 'content'], dtype='object')

In [39]:
df[df['title'].isna()]

Empty DataFrame
Columns: [url, title, content]
Index: []

In [40]:
df.to_json("4300_transcripts.json", orient="records", lines=True)

In [43]:
df.loc[444, 'content']

"In this comedy special taped at DAR Constitution Hall, his first solo special on the network in seven years, Williams covers such topics as global warming, sex and politics, the state of health care in the country (suggesting a cash for clunkers program for elderly relatives, among other things), drugs – recreational and otherwise – and more personal topics, including his recent heart surgery.\nOriginal Air Date on December 6, 2009\n* * *\n[audience cheering, applauding]\n[rock music playing]\nAnnouncer: Ladies and gentlemen, Please welcome Robin Williams!\n[cheering]\nNo! Please. Sit down! Thank you! Thank you! What’s up, D.C.? Yes, indeed! Yes, indeed! [cheering, hooting] Wow, thank you. Mmm. Thank you. Please, I’ve had heart surgery. Thank you. It’s nice to be in Washington, where the buck stops here. Way to go. And then it’s handed out to A.I.G. and many other people. Now… I have the new Timothy Geithner $20-bill. It’s just been printed, kind of neat. Instead of “in god we trust,” It just says “trust me.” And it says “spend before Tuesday.” And also instead of Andrew Jackson, it has the little man from monopoly going– and I know many of you have been looking for Sarah Palin’s book. It is a bitch to find. Good luck. I found it somewhere between fiction and non-fiction in the fantasy aisle. It was kind of fun. Wonderful. Do you get– do you get the feeling with Sarah Palin, In high school she was voted least likely to write a book and most likely to burn one? Do you think that might’ve been– she’s pretty wild. Baby, I love her. And also, Oprah– Oprah has retired– Is gonna retire her show. Please say it isn’t so! Oprah’s gonna retire her show. I hope she’s not bummed out about losing the Olympics. I hope that’s not it. It wasn’t really fair. Chicago sent Oprah and Michelle, Brazil sent 50 strippers and a pound of blow. It’s like, what? Do you think the Olympic committee was going “Oprah? Shaved pussy? Oprah, would you– okay, we’re gonna have to go this way.” And who the fuck thinks that Rio is safer than Chicago?! My God. They’re gonna have to make kidnapping and waxing Olympic events. Degree of difficulty: 5.3. [mimics ripping noises] But it is interesting. They have the Winter Olympics in Vancouver and the torch is heading across Canada right now and already in B.C. they’re lighting torches going– [choked] “we’re waiting.” Come on, you folks who just came from Capitol Hill. Come on down. Where do you go? How are you, my friends? Grab some seats. – You were caught in– – [audience shouting] What? – [woman shouts] – that’s your old boss? Did you fuck him? Sorry. Okay. Not an inappropriate question to ask in Washington. No. And he’s going, “no! No! She was just a page, it’s okay!” And it was weird.\nIn California this summer all the State Parks caught on fire which was sad because these parks are full of\nweed\n. It’s bad news. It’s like– even the guys fighting the fires are like… [laughing] “fuck! Oh my God! Make another rainbow, Tommy! Oh my God!” It’s weird. Even Smokey the Bear was going, “only you can– Shit, I knew this. Fuck.” And California weed is kick-ass fucking weed. This is weed that even Jamaicans go, “oh, don’t smoke that weed, man.” It’s California catatonic. It’s the type of weed you hit it and it’s like… Fuck! Shit! I’m not doing something. What is it? Oh right, breathe! [exhales] And you get so stoned, you end up sitting on your couch for a week to the point where your cat’s going, “get up, you asshole! I’ve been eating my own shit for the last two days! I know I’m mellow, but this is fucking ridiculous!” And if they legalize it, they’re going to have to regulate it and they’re going to have to a warning on a box of joints. It’s going to have to say, “Surgeon General has determined this will make your music awesome. Even Yanni. And if you thought you enjoyed cartoons before…” and if they’re gonna have ads– they’re gonna have ads and it’ll be like instead of the Marlboro man, it’ll be the Mendocino man. It’ll be a cowboy on the back of a horse going, “shit, am I thirsty. God damn.” Even the horse will be going, “I don’t know where the fuck I am. God damn, I got a little cotton mouth here. God damn it.”\nAnd the weird fucking thing with these weather systems– the storms right now have been fucking insane. Kick-ass tornados in the midwest. It used to be in the midwest when you had a tornado, it was like everybody get in the root cellar. Not anymore. You fuckers are like “get a video camera! Get outside! Film it, Bobby!” How’s the tornado? “it just blew my pants off. Keep shooting. Fuckin’-a!” You know the difference between a tornado and divorce in the South? Nothing. Someone’s losing their trailer, number one. It’s like, mmm! God damn! The hurricanes have been getting bigger and fucking bigger. And they usually give them names that don’t really inspire fear. Like hurricane Terrence does not inspire fear. This sounds like a slightly gay hurricane. Where are you going? “I might go to Boca. I might go to South Beach. I don’t know. All I know is blowing is involved. Yes!” And they should name the hurricanes After the people it’s gonna be fucking with. If it’s going to Texas– hurricane Billy Ray. Come on now. What are you gonna do? “fuck shit up! That’s what goes on.” If it’s off the coast of Miami– hurricane Bernie. “hello! He took our 401k. The goniff’s coming back for the house. Move out! Let’s fucking go!” And when they named a hurricane Hurricane Ike, I went, finally, they have the balls to name a hurricane after a crack-smoking, wife-beating motherfucker. Yeah! Even Tina Turner would go, “you’d better get your shit and get out of the house. ’cause Ike never does anything nice and easy. Never.” And the hurricanes have been getting so big that even the guy on the weather channel is freaked out. He’s going, “okay, let’s go to our new hurricane weather map– Fuck! This is hurricane Shavon. The map is the entire South The asshole in the middle is Dallas. Um, crazy. Back to you, Ted. I just shit myself.” And they always go down to some poor fuckers on the coast in the middle of the storm hoing, “Carl, how’s it down there on the coast?” “not bad! Seems to be kicking up!”\nAnd then there’s always the aftermath where they interview some family standing in the wreckage of their beach house and they’re always going like, “hurricane came and tore everything up. And we had just rebuilt.” Time out. How often do you rebuild? “every year.” Why do you rebuild here? “we love the view.” Well, you may want to get some styrofoam furniture that goes up and fucking down. Some things that you can hose off maybe.\nBut the weird thing is, I can’t give them shit. I like in California. I live on God’s etch-a-sketch. It’s crazy. We have\nearthquakes\nevery other day. And you get kind of blasé. Like, “oh, fuck. 2.5, not bad. Oh, shit! 5.8. Maybe we should have drinks outsides. Let’s go.” And they always talk about the big one. I was in a 7.5 earthquake. That was a “fuck me” moment. That was a– [screams] And they went, “that was not the big one.” Really? Well, what will the big one be? “well, in the big one, if there is the big earthquake, Nevada will be wine country, number one.” And when will the big one be? “well, we have a window of opportunity.” Well, what will that be? “could be tomorrow… or 10,000 years from now.” Well, thanks for the fucking heads-up.\nThe only warning you have is if your cat is spread-eagle in the doorway like– [howls] get the fuck out. And if your parrot starts going, “pack the car! Pack the car! Food and water! Food and water!” Also, if you have a parrot, do not leave them in the bedroom. They hear everything. All of the sudden you’ll have guests over for dinner and the parrot will go “not the ass.” whoa-ho-ho! Petey! [chuckles] he’s been watching porn again. “fuck me, Teddy! Fuck me hard!” Honey, who’s Teddy? Hmm.\nAnd the weird thing is you try and do your part to reduce your carbon footprint. And if you have a hybrid, God bless you, sweet cars. But especially if you drive them outside a major city, you get into little cities especially in the South, it becomes kind of interesting. you pull into a small gas station, it’s like, “what the fuck is this? Bobby, get over here. It’s one of them new inbreds! Look at this motherfucker. Shit, looks like Volkswagen fucked a golf cart. God damn. I did not hear you come in. You may want to put some cards in the spokes of your wheels so you make some fucking noise.” That’s why there’s not gonna be any\nNASCAR\nhybrid race. A NASCAR hybrid race would be like, “here they come.” [blowing softly] And I love the guys who say, “I watch NASCAR for the racing.” Yeah, I watch porn for the acting. You liar! You watch NASCAR to see team viagra spin out in flames and the guy get out with his pubes on fire going, “I’m okay!” And there was a guy in the South who said, “they should have NASCAR in the Olympics.” And it was like, mm-hmm. At that moment ever Darwin was going, “come with me.” This is the ascent of man. You stand here. But it’s weird too. If you recycle, God bless you. You recycle, good for you, congratulations. But if you recycle, there is one group who is really pissed off. That group are the raccoons. They are going through your recycling like, [irish accent] “what the fuck is this shit? Where are the hefty bags? The piñata of life that used to feed an entire fucking family? This is glass and plastic. I can’t digest this shit, you green asshole! I’m spreading this shit all over your lawn! I’m taking a dump in your pool too.” I don’t know why I made the raccoons Irish, but it works. Now… and they’re ballsy little motherfuckers too. You turn on the light, they look at you like, “what the fuck you gonna do? I got a skunk as backup. Don’t make me call him.” And they’ve got those little jazz paws. “jazz paws!” They can open doors, cabinets. I’m amazed you don’t come home and find them on the computer going, “I’m ordering shit. How you doing? The dog knows I’m here. I locked him in the fucking closet. He’s an idiot. Too late.” And the deer in California have total amnesty ’cause they know no one’s gonna cap their ass and strap them to the front of a Ranger Rover and go downtown for a mocha. They walk through your yard like supermodels with hooves. Like, “hi. Are these your roses? Oh my God, a deer fence.” [makes whooshing noise] And I love the five point buck that jump out in front of your car like, “I hope you’re insured. ’cause I’m taking you out. This is revenge for my brother who’s hanging in a bar in Tennessee. Fuck you.” And we have coyotes, which are like dogs on crack. They come into your yard looking like, “hey! I’m a dog. Ooh! Ooh, I’m a fucking dog. Hey! Psst, listen. Do you have any small animals you don’t need?” And I’m sure your cat is sitting in the back going, “I will shit in the box! Don’t send me out there. Those things eat pussy! Don’t send me out there!” [hisses] And if you have a cat a a dog… and they live together, do you think your cat mind-fucks your dog? I don’t think it’s fair. I think the moment you go to sleep the cat’s like, “Scooby!” [hisses] “yeah yeah?” “hey, Scooby, are you man’s best friend?” “oh God, yeah. I love him. I love him!” “really? Then where are your balls?” “shit, they were there yesterday. I wondered why my ass tasted differently.” “I’m just saying that’s weird. You know, I’m just saying–” [hacking] “I’m just saying that’s weird, that’s all I’m saying.” And people in California give their cats prozac. How much more mellow can a fucking animal be? But that’s California, where animals have better healthcare than the rest of the country. It’s fucking insane. And if the whole healthcare debate– If you want to know how your congressman and senators are gonna vote, we should actually– maybe they should be like NASCAR drivers. They should actually have to have jackets with the names of all the people who are sponsoring them. Wouldn’t that be cool? Fuckin’-a! Yeah, baby. Then you might have a clue to why the fuck they voted that way. “big drug company.” got it! Thank you. And I have an alternative healthcare plan. It’s called cash-for-clunkers- for-older-relatives. It’s kind of fun. You sell grandma for parts. Grandma, you’ve got two kidneys. We need a porch. Let’s do this. And do not sell grandma’s kidneys to that Hasidic Rabbi in New Jersey. Fuck. Who buys organs from a Hasidic Rabbi Going, “I’m crazy Itzhak. Come on down. I’m verklempt with values. Come on down! I’ve got kidneys. I’ve got livers. How’s the liver? Fresh! Come on down! and if you order now, you’ll get this lovely wallet made from a Hasidic foreskin. You rub it, It becomes a suitcase. Come on down! Come on down! I’m open 24/6 for you! Come on!”\nAnd if you have an older relative living with you that has dementia, and the temarketers are calling, put her on the phone with the telemarketers.\n[laughter and applause]\nIt works. After two hours she thinks she’s talking to your long-lost cousin Carl, and the fucking telemarketers will NEVER call back again.\n[laughter]\nAnd it’s weird too, ’cause I had\nopen heart surgery\nwhich lets you know exactly what the fuck it is– open heart. An angiogram does not let you know what they’re going to do. An angiogram is where they go through your groin to your heart. And how knew that the way to man’s heart was through his groin? And the women– many women are going, “we’ve known that forever. Yes. Simple. You grab a man’s balls, his heart will follow.” And I found out I had a bad heart because they did an echocardiogram and my heartbeat was like– [mimics irregular beating] My cardiologist went, “that’s not good.” My latin friend said, “no, you could dance to that. That’s kinda cool.” And then they did the angiogram and I heard my– [blowing raspberries] I had a blown valve which makes me sound like a Chevrolet. Like what the fuck? And they started offering me choices about what type of valves I could get. And here were some of my choices: Number one– a porcine valve Which is a pig valve, which is kind of cool because you’re already inoculated for swine flue, number one. And one of the side effects is you can find truffles, which is kind of cool. I was hoping to get an equine valve ’cause then you can hang out of your shorts like, “oh my God.. Baby, I’m sorry. I just got excited.” You know? To get out of the house, you have to have a midget jump on your back going, “we’re going outside right now. How many months since the surgery?” five. And they offered me a mechanical valve which is kind of cool. I thought, maybe I can get the new Apple iheart. That would be great. It comes with 20,000 emotions and that would be– and I thought, wait a minute. if I could get an iheart, ladies, how about this? Instead of breast implants– Speakers. Wouldn’t that be cool? We’ll call ’em blue tits, they’ll be compatible with the heart. And if you can’t afford speakers, just put in a squeak toy. We’re that simple. That’d be great. A lot of you men would be going– [squeaks] “oh yeah, baby.” [squeaking] [laughing] And I’ll put a whistle in my dick so when you blow me– Whoo! Kind of fun, but… I ended up getting a bovine valve which is a cow valve. Which is kind of cool, ’cause you can shit standing up.\nThat’s great. Great to be here. Nice to be here. But after the surgery, you get very emotional. It’s like– it’s like weird. People go, “how are you?” [crying] God, thanks for asking. And I got so emotional, I thought instead of a valve They gave me a tiny vagina. Which is like– what? “how are you?” much better now, thank you. Mmm. Oh God. Don’t use the paddles, just rub me here. There we go. And if this is the symbol for men, Is this the symbol for women? Don’t jerk me off. I won’t. God bless. Thank you. And the surgery– the surgery went amazing. I had a doctor who had done 4,000 surgeries. All of them fucking amazing. That was great. You don’t want a doctor who’s done six surgeries, three of them haven’t gone that well. You don’t want a guy going, “let’s see what happens.” And the surgery was pretty amazing. It went fantastic. First thing to come back online, Your heart– [beeps] Great. And then your brain. Last thing, asshole. [grunts] The drugs make you so constipated, I thought they were gonna have to bring in a priest to do a rectal exorcism. Demon turd, fall from his ass! The power of fiber compels you! The power of fiber compels you! And after the surgery, they put you on a little self-medicator, which is fucking great. You’re like… [laughs] I want to thank my anesthesiologist, ’cause I don’t fucking remember his name. And the drug they gave me for the surgery was a drug called propofol which is nicknamed milk of amnesia. Fucking insane drug. I had that in a surgical situation. Michael Jackson was taking propofol at home To sleep. Fuck off. A doctor said, “taking propofol to sleep is like doing chemotherapy because you’re tired of shaving your fucking head.” It’s like, no. And do you think that when you die and you get to the other side in the afterlife They give you things you had in life? Like Michael got to the other side and it’s like, Michael? [high voice] “yes?” We have some of your things here. “really?” One african-american nose. Is this yours? “yes.” We have four others here. Are these yours? “three of them are mine. One’s Latoya’s.” But you can’t blame Michael.\nWe’re a\nheavily medicated society\n. All the drugs we take: Prozac, Effexor, Valium. I thought for the last ten years, we’ve been on some weird fucking drug – the whole country – called “Fukitol.”\n[\nlaughter\n]\nWhat a weird fucking drug. And we’re just coming out of it and we’re kind of waking up.\n[cheers and applause]\nFuckin’ A! It’s weird. It’s like you’re going “last thing I remember was the economy was working and there was a budget surplus.” Yeah! “Where’s\nClinton\n?” We impeached him. “Fuck!”\n[laughter]\n“For what?” A blowjob. “Wow! Who did he blow, Putin?”\n[laughter]\nNo! No, he got blown by a Jewish girl. “Wow! He got head from a Jewish girl? Fuckin’ A! And they impeached him for that?” Well, he lied about it. “He’s married! Who wouldn’t? What the fuck?”\n[laughter]\nNo, he lied about it to Congress. “And THOSE fuckers impeached him? That’s like a group of lepers judging a beauty contest. What the fuck?”\n[laughter]\n“Wow, that’s nuts!” And then they acquitted him. “Oh, cool. And who was president next? Gore?” No,\nBush\n. “He was already president!” No, this was his son. “Oh, the one from Florida. He’s kinda cool.” No, the one from Texas. “JUNIOR? Fuck! My God, he… the one who traded Sammy Sosa?” Fuck yeah! “How was he as president?” Kinda goofy. “Really?” He waved at Stevie Wonder.\n[laughter]\n“What the fuck!” It’s like, “Wow! And then what did he do?” Well, he took a lot of vacations. “And then what happened?” We got attacked. “By who?”\nOsama bin Laden\n. “That guy from Afghanistan? Didn’t we used to send him weapons?” Yeah, I know! “We went after him, right?” Yeah. “Did we get him?” Almost.\n[laughter]\n“Well, what do you mean ‘almost’?” Well, we went after Hussein, because he had weapons of mass destruction. “That guy from Syria. I knew that fuck would do this.” No, the one from Iraq. “SADDAM Hussein? Bush Sr. kicked his ass!” Yeah, he did! “And we got him?” Oh, fuck, we got him. “And we found the weapons of mass destruction? Cause he would tell you where they are.” Well, they executed him. “Fuck off! And did you get bin Laden?” Almost. We got four of his number threes. “Okay. But he’s in Afghanistan.” Maybe. He might be in Pakistan. “Well, let’s go after him in Pakistan!” Well, there’s a problem there. They’re allies, and they have weapons of mass destruction. “Oh, no! What about the economy?” Well, we had to bail out the banks. “Again?” Fuck, yeah! “And now, who’s the president?” A black guy. “Oh, yeah right.” Yeah, there’s a black president and a Latino on the Supreme Court. “There is? Oh, my God! Who’s the president? Jesse Jackson?” No, his name is Barack 